[profile.default]
src = "src"
out = "out"
test = 'test'
cache_path = 'cache'
libs = ['node_modules', 'lib']


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
